# Generated by Django 4.2.7 on 2023-12-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id_book", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=50)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id_student", models.AutoField(primary_key=True, serialize=False)),
                ("lastname", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("Registration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id_loan", models.AutoField(primary_key=True, serialize=False)),
                ("loan_date", models.DateField()),
                ("duration", models.IntegerField()),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listings.book"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.student",
                    ),
                ),
            ],
        ),
    ]
